# Generated by Django 5.1.1 on 2024-10-07 03:31

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models

import apps.book.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1),
                                                       django.core.validators.MaxValueValidator(5.0)])),
                ('summary', models.TextField(max_length=3000, unique=True)),
                ('full_audio', models.FileField(blank=True, null=True, upload_to='')),
                ('ebook', models.FileField(upload_to=apps.book.models.get_ebook_upload_path)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books',
                                             to='author.author')),
                ('categories', models.ManyToManyField(related_name='books', to='category.category')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
