# Generated by Django 5.1.1 on 2024-10-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_url',
            field=models.URLField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='audiobooks/covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ebook',
            field=models.FileField(blank=True, null=True, upload_to='audiobooks/ebooks/'),
        ),
    ]
