# Generated by Django 5.1.1 on 2024-10-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_cover_url_book_ebook_url_book_poster_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ebook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
