# Generated by Django 5.1.1 on 2024-09-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('category', '0002_rename_title_category_name'),
        ('user', '0002_remove_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(related_name='users', to='category.category'),
        ),
    ]
