# Generated by Django 5.1.1 on 2024-09-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_title_category_name'),
        ('user', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='users', to='category.category'),
        ),
    ]
