# Generated by Django 5.1.1 on 2024-09-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_title_category_name'),
        ('user', '0009_usercategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategory',
            unique_together={('user', 'category')},
        ),
    ]
