# Generated by Django 5.1.1 on 2024-10-04 16:40

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('chapterId', models.AutoField(primary_key=True, serialize=False)),
                ('chapterName', models.CharField(max_length=255)),
                ('chapterUrl', models.URLField(max_length=1000)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('title', models.CharField(max_length=255)),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1),
                                                       django.core.validators.MaxValueValidator(5.0)])),
                ('summary', models.TextField(max_length=3000)),
                ('full_audio_url', models.SlugField(max_length=1000)),
                ('pdf_url', models.FileField(upload_to='ebooks/')),
                ('is_recommended', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks',
                                             to='base.author')),
                ('categories', models.ManyToManyField(related_name='ebooks', to='category.category')),
                ('chapters', models.ManyToManyField(related_name='ebooks', to='base.chapters')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
