# Generated by Django 5.1.1 on 2024-10-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pdf_url',
            new_name='ebook',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_recommended',
        ),
        migrations.AlterField(
            model_name='book',
            name='full_audio_url',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
