# Generated by Django 5.1.1 on 2024-10-04 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0002_rename_pdf_url_book_ebook_remove_book_is_recommended_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='full_audio_url',
            new_name='full_audio',
        ),
    ]
